Repository guilhermevieirasilvagoncalves/Source-Code-Inspection, pull requests merged in 2024-10, with the labels that each got.

#17 Ajuste | ID 1
  Source Code Inspection/src/br/calebe/ticketmachine/core/TicketMachine.java
Labels: bug

#18 Ajuste | ID 3
  Source Code Inspection/src/br/calebe/ticketmachine/core/Troco.java
Labels: bug

#20 Ajuste | ID 6
  Source Code Inspection/src/br/calebe/ticketmachine/core/Troco.java
Labels: bug

#21 Ajuste | ID 8
  Source Code Inspection/src/br/calebe/ticketmachine/core/Troco.java
Labels: bug

#23 Ajuste | ID 4
  Source Code Inspection/src/br/calebe/ticketmachine/core/TicketMachine.java
Labels: bug

#25 Ajuste | ID 3
  Source Code Inspection/src/br/calebe/ticketmachine/core/Troco.java
Labels: bug

#26 Ajuste | ID 14
  Source Code Inspection/src/br/calebe/ticketmachine/core/TicketMachine.java
Labels: bug

#27 Ajuste | 12
  Source Code Inspection/src/br/calebe/ticketmachine/core/PapelMoeda.java
Labels: enhancement

#28 Ajuste iteracao
  Source Code Inspection/src/br/calebe/ticketmachine/core/Troco.java
Labels: bug

#29 Ajuste | ID 11
  Source Code Inspection/src/br/calebe/ticketmachine/exception/PapelMoedaInvalidaException.java
Labels: invalid

#30 Ajuste exception saldo insuficiente
  Source Code Inspection/src/br/calebe/ticketmachine/exception/SaldoInsuficienteException.java
Labels: invalid
